### ISSUE TITLE
Putting all apps into 1 app

### ISSUE THREAD

**Issue by tongantopdog** [MilesOtt/bayes-rules-shiny#15]
@MilesOtt I think I found a way for us to compile all the apps. When I run it through R it works perfectly, but when I  publish it, I get an error for where the graphs should be. Any ideas? I pushed my changes. If you open chapter 1's server and ui and then go to links, you can see what I did. 

Let me know your thoughts

**Comment by tongantopdog** [comment]
Ope, I figured it out!

**Comment by MilesOtt** [comment]
Wow so cool! Way to go!!!! 

Does the shiny free server count this as two apps or as one app?

**Comment by tongantopdog** [comment]
It counts as one! All running under chapter 1.

**Comment by MilesOtt** [comment]
WOOOHHHHHHH we are in business lol!

**Comment by MilesOtt** [comment]
OK let's reopen this issue and have you put **all** of the apps in the one app?

**Comment by tongantopdog** [comment]
You got it!

**Comment by MilesOtt** [comment]
woot woot! Thanks @tongantopdog

**Comment by MilesOtt** [comment]
shiny professional over heeerrereeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by tongantopdog** [comment]
Lollllll thank you!!! I finished compiling it. You can check it out at my shiny app.io page under ch_1_quiz 1

**Comment by tongantopdog** [comment]
Let me know your throughts

**Comment by MilesOtt** [comment]
Wow looks great! Can you add the other apps that you didn't get shiny.io to host? I am curious to see if you can have more than 5 apps linked in here. Loving this development :)

**Comment by tongantopdog** [comment]
Okidokie. These are the ones I've made so far, including ch.3 , but I can go ahead and create the most recent one for Ch 4 and see how that works!

**Comment by tongantopdog** [comment]
Also, if you have any more ideas for apps to make, I can try and add them in by Sunday!

**Comment by MilesOtt** [comment]
You did it @tongantopdog I am going to close this issue :)
